suppressPackageStartupMessages(library(data.table))
out<-normalizePath(Sys.getenv('MR_SENSITIVITY_DIR','.'),mustWork=TRUE)
expected<-sort(list.files(file.path(out,'pairs'),pattern='\\.rds$'))
actual<-sort(list.files(file.path(out,'presso'),pattern='\\.rds$'))
stopifnot(length(expected)==58,identical(expected,actual))
rows<-lapply(actual,function(name){
 z<-readRDS(file.path(out,'presso',name))
 stopifnot(z$status %in% c('COMPLETED','FAILED','NOT_ESTIMABLE'))
 if(z$status=='COMPLETED')stopifnot(is.list(z$result),length(z$result)==2)
 data.table(pair=sub('\\.rds$','',name),status=z$status,nsnp=if(is.null(z$nsnp))NA_integer_ else z$nsnp,detail=if(is.null(z$reason))'' else z$reason,implementation=if(is.null(z$implementation))'' else z$implementation)
})
fwrite(rbindlist(rows,fill=TRUE),file.path(out,'presso_status.csv'))
writeLines('All 58 cached pairs verified readable; inspect status table for estimation status',file.path(out,'PRESSO_COMPLETE.txt'))
print(table(rbindlist(rows)$status))
